#! /bin/sh
#
# ptu-forwarder 		ptu-forwarder daemon
#				Daemon to forward sensor readings on the network
#
# Authors:	 Christos Papachristou <papachristou@novocaptis.com>
#
# Version:	0.1
#

set -e

. /etc/profile
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="ptu-forwarder daemon"
NAME="PTU_forwarder_TCP_RS232"
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
USER=root
	
# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#
#	Function that starts the daemon/service.
#
d_start() {
	if start-stop-daemon --start --quiet --test --pidfile $PIDFILE \
		--user $USER --exec $DAEMON -- $DAEMON_OPTS > /dev/null ;then
	
	echo Turn off 3.3V supply
	gpio_set 21 0
	echo Turn off 5V supply
	gpio_set 22 0
	echo sleep for 0.5 secs
	sleep 0.5
	echo Turn on 3.3V supply
	gpio_set 21 1
	echo Turn on 5V supply
	gpio_set 22 1
	
	start-stop-daemon --start --quiet --make-pidfile --background --pidfile $PIDFILE \
		--user $USER --exec $DAEMON -- $DAEMON_OPTS
		else
			echo PTU_forwarder_TCP_RS232 already running
	fi
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		 --oknodo --user $USER --exec $DAEMON
}


case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	d_start
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	d_stop
	echo "."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
