#! /bin/sh
#
# startstopscripts	scripts to run at system startup and shutdown	
#
# Authors:	 Christos Papachristou <papachristou@novocaptis.com>
#
# Version:	0.1
#

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="system start and stop scripts"
NAME="startstopscripts"
DAEMON=/usr/sbin/wpss-system.sh
#PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
USER=root

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#
#	Function that starts the daemon/service.
#
d_start() {
	wpss-system.sh start
#	start-stop-daemon --start --quiet --make-pidfile --background --pidfile $PIDFILE \
#		--user $USER --exec $DAEMON -- $DAEMON_OPTS
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	wpss-system.sh stop
#	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
#		 --oknodo --user $USER --exec $DAEMON
}


case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	d_start
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	d_stop
	echo "."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
